# Generated by Django 2.2.9 on 2020-01-28 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='household',
            old_name='member',
            new_name='members',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='household',
            new_name='households',
        ),
    ]
