# Generated by Django 2.2.9 on 2020-01-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='avatar',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
