# Generated by Django 2.2.9 on 2020-01-24 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Member'),
        ),
    ]
