# Generated by Django 2.2.9 on 2020-01-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_member_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='avatar',
            field=models.CharField(default='/static/images/no_avatar.webp', max_length=200),
        ),
    ]
