# Generated by Django 2.2.9 on 2020-01-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200124_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='member',
            field=models.ManyToManyField(related_name='members', to='main_app.Member'),
        ),
        migrations.AlterField(
            model_name='member',
            name='household',
            field=models.ManyToManyField(related_name='households', to='main_app.Household'),
        ),
    ]
