# Generated by Django 2.2.9 on 2020-01-27 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200127_2006'),
        ('main_app', '0003_auto_20200127_1930'),
    ]

    operations = [
    ]
